# Test joutest with itself
[[tests]]
files = "tests/tests_of_joutest/**/joutest.toml"
command = ["joutest", "--no-colors"]
cd_to_containing_directory = true
output_comment_rules = {
    Output = '{comment}',
    Error = 'joutest error in file "{file}", line {line}: {comment}'
}

[[tests]]
files = "tests/tests_of_joutest/should_succeed/verbose*/joutest.toml"
command = ["joutest", "--no-colors", "--verbose"]

[[tests]]
files = "tests/tests_of_joutest/bad_configs/**/joutest.toml"
expected_exit_code = 1

[[tests]]
files = "tests/tests_of_joutest/bad_configs/command_not_found/joutest.toml"
command = {
    windows = ['cmd', '/c', '..\..\..\..\joutest --no-colors | ..\..\..\..\jou windows_output_hack.jou'],
    default = ['joutest', '--no-colors'],
}

[[tests]]
files = "README.md"
