#########################
# Test the Jou compiler #
#########################
#
# These tests are still partially done by runtests.sh. I am in the middle of
# moving runtests.sh tests here, and likely will be for quite some time.
#
# TODO: examples/memory_leak.jou will need to be skipped once valgrind gets
#       involved. Previously it was always silent-skipped, and IMO that's fine.
#
# TODO: tests/should_succeed/compiler_unit_tests.jou will need to be skipped
#       when running under valgrind. Apparently LLVM leaks memory when the
#       program starts, even if it is never called.

[[tests]]
files = [
    "examples/*.jou",
    "examples/aoc*/day*/part*.jou",
    "tests/should_succeed/**/*.jou",
]
output_comment_rules = {
    Output = '{comment}',
    Warning = 'compiler warning for file "{file}", line {line}: {comment}'
}
output_comment_order = ["Warning", "Output"]

[[tests]]
files = [
    "tests/404/*.jou",
    "tests/already_exists_error/*.jou",
    "tests/other_errors/*.jou",
    "tests/syntax_error/*.jou",
    "tests/too_long/*.jou",
    "tests/wrong_place/*.jou",
    "tests/wrong_type/*.jou",
]
output_comment_rules = {
    Warning = 'compiler warning for file "{file}", line {line}: {comment}',
    Output = '{comment}',
    Error = 'compiler error in file "{file}", line {line}: {comment}',
    ErrorNoLine = 'compiler error in file "{file}": {comment}',
}
output_comment_order = ["Warning", "Output", "Error", "ErrorNoLine"]
expected_exit_code = 1

# TODO: These files are still tested with legacy runtests.sh
[[tests]]
files = [
    "tests/404/file.jou",
    "tests/other_errors/source_file_contain_zero_byte.jou",
    "tests/should_succeed/compiler_cli.jou",
    "tests/should_succeed/intnative_test.jou",
    "tests/should_succeed/link_with_liblzma_relative_path.jou",
    "tests/should_succeed/sizeof.jou",
    "tests/wrong_type/pointer_to_integer_32bit.jou",
    "tests/wrong_type/sort_comparator.jou",
]
skip_mode = "skip_normally"

# Don't run files that are only meant to be imported
[[tests]]
files = "tests/should_succeed/imported/*.jou"
skip_mode = "skip_silently"

# This is a command-line program that expects some arguments to be present
#
# The exit code from the program is actually 2, but the jou compiler is a bit
# funny and instead exits with 1.
[[tests]]
files = "examples/replace.jou"
expected_exit_code = 1

[[tests]]
files = [
    # AoC files use fopen("sampleinput.txt", "r")
    "examples/aoc*/day*/part*.jou",
    # double_dotdot_import test had a bug that was reproducible only with relative path.
    "tests/should_succeed/double_dotdot_import/*/*.jou",
    # Perlin noise example writes to a file. We want that file to end up in the examples
    # folder, not in project root.
    "examples/perlin_noise.jou",
]
# We don't do this for all files, because I like long but relative paths in error messages.
cd_to_containing_directory = true


############################
# Test joutest with itself #
############################
[[tests]]
files = "tests/tests_of_joutest/**/joutest.toml"
command = ["joutest", "--no-colors"]
cd_to_containing_directory = true
output_comment_rules = {
    Output = '{comment}',
    Error = 'joutest error in file "{file}", line {line}: {comment}'
}

[[tests]]
files = "tests/tests_of_joutest/**/*verbose*/joutest.toml"
command = ["joutest", "--no-colors", "--verbose"]

[[tests]]
files = [
    "tests/tests_of_joutest/bad_configs/**/joutest.toml",
    "tests/tests_of_joutest/test_failures/**/joutest.toml",
]
expected_exit_code = 1

[[tests]]
files = "tests/tests_of_joutest/bad_configs/command_not_found/joutest.toml"
command = {
    windows = ['cmd', '/c', '..\..\..\..\joutest --no-colors | ..\..\..\..\jou windows_output_hack.jou'],
    default = ['joutest', '--no-colors'],
}


###############################
# Test code in markdown files #
###############################
[[tests]]
files = ["README.md", "doc/**/*.md"]
markdown_code_block_languages = ["python"]
output_comment_rules = {
    'Output' = '{comment}',
    'Warning' = 'compiler warning for file "{file}", line {line}: {comment}',
    'Error' = 'compiler error in file "{file}", line {line}: {comment}',
}
skip_mode_if_no_expected_output = "skip_silently"

[[tests]]
files = "doc/assert.md"
# Change the file name shown in error messages
command = ["jou", "--stdin-name", "test.jou", "-"]
# TODO: This setting doesn't exist. Ideally joutest would show line numbers
#       relative to the code block in markdown file, not the whole markdown file.
#       Usually the joutest default is good, but not for showing assertion errors.
#add_newlines_to_fix_markdown_line_number = false
skip_mode = "skip_normally"

# Ignore exit codes for code in markdown that intentionally fails to compile or run
#
# TODO: add a better way to do this.... Ideally "# Error:" anywhere would mean
#       exit code 1, but I'm not sure what the appropriate joutest feature to
#       support that would be. So we ignore the exit codes for now.
[[tests]]
files = [
    "doc/compiler_internals/type-checking.md",
    "doc/keywords.md",
    "doc/match.md",
    "doc/tutorial.md",
    "doc/types.md",
]
command = {
    # Apparently ver>nul is the Windows cmd equivalent of "true".
    # https://stackoverflow.com/a/47318952
    windows = ["cmd", "/c", 'jou --stdin-name {file} - || ver>nul'],
    default = ["sh", "-c", "jou --stdin-name {file} - || true"],
}
