all: jou.exe

jou_bootstrap.exe: bootstrap.sh bootstrap_transpiler.py
	bash ./bootstrap.sh

jou.exe: jou_bootstrap.exe $(wildcard compiler/*.jou compiler/*/*.jou)
	./jou_bootstrap.exe -o jou.exe compiler/main.jou

# Does not delete tmp/bootstrap_cache because bootstrapping is slow.
.PHONY: clean
clean:
	bash -O extglob -c "rm -rvf tmp/!(bootstrap_cache)"
	rm -vf *.exe
	find . -name jou_compiled -print -exec rm -rf '{}' +
