CFLAGS += -Wall -Wextra -Wpedantic
CFLAGS += -Werror=switch -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -Werror=implicit-fallthrough
CFLAGS += -std=c11
CFLAGS += -g

SRC := $(wildcard src/*.c)
OBJ := $(SRC:src/%.c=obj/%.o)

ifneq (,$(findstring Windows,$(OS)))
	include Makefile.windows
else
	include Makefile.posix
endif


# TODO: put this back
#self_hosted_compiler$(EXE): jou$(EXE) config.jou $(wildcard self_hosted/*.jou)
#	./jou -O1 -o $@ --linker-flags "$(LDFLAGS)" self_hosted/main.jou
#config.jou:
#        echo "# auto-generated by Makefile" > $@
#        echo "def get_jou_clang_path() -> byte*:" >> $@
#        (if echo $$OS | (grep Windows); then \
#                echo "    return NULL" >> $@; \
#        else \
#                echo "    return \"`$(LLVM_CONFIG) --bindir`/clang\"" >> $@; \
#        fi)
