#!/bin/bash
set -e

jou -o toml_parser toml_parser.jou

# Make sure all error messages are mentioned in expected_errors.toml
diff -u --color=always <(./toml-test-* list | grep ^invalid) <(grep '^"' expected_errors.toml | cut -d'"' -f2)

tests_to_skip=(
    # These tests contain dates or times, so they are not supported
    valid/array/array
    valid/comment/everywhere
    valid/datetime/datetime
    valid/datetime/edge
    valid/datetime/leap-year
    valid/datetime/local
    valid/datetime/local-date
    valid/datetime/local-time
    valid/datetime/milliseconds
    valid/datetime/timezone
    valid/spec-1.0.0/local-date-0
    valid/spec-1.0.0/local-date-time-0
    valid/spec-1.0.0/local-time-0
    valid/spec-1.0.0/offset-date-time-0
    valid/spec-1.0.0/offset-date-time-1
    valid/spec-example-1
    valid/spec-example-1-compact

    # TODO: Figure out why these fail, fix as appropriate
    valid/array/array-subtables
    valid/array/open-parent-table
    valid/example
    valid/inline-table/key-dotted-04
    valid/key/dotted-04
    valid/key/like-date
    valid/key/quoted-unicode
    valid/spec-1.0.0/array-of-tables-0
    valid/spec-1.0.0/array-of-tables-1
    valid/spec-1.0.0/table-7
    valid/string/quoted-unicode
    valid/string/unicode-escape
    valid/table/array-empty
    valid/table/array-empty-name
    valid/table/array-implicit
    valid/table/array-implicit-and-explicit-after
    valid/table/array-many
    valid/table/array-nest
    valid/table/array-one
    valid/table/array-table-array
    valid/table/array-within-dotted

    invalid/array/extend-defined-aot
    invalid/array/extending-table
    invalid/array/tables-01
    invalid/array/tables-02
    invalid/control/rawmulti-del
    invalid/control/rawmulti-lf
    invalid/control/rawmulti-null
    invalid/control/rawmulti-us
    invalid/control/rawstring-cr
    invalid/control/rawstring-del
    invalid/control/rawstring-lf
    invalid/control/rawstring-null
    invalid/control/rawstring-us
    invalid/control/string-bs
    invalid/control/string-cr
    invalid/control/string-del
    invalid/control/string-lf
    invalid/control/string-null
    invalid/control/string-us
    invalid/datetime/y10k
    invalid/encoding/bad-codepoint
    invalid/encoding/bad-utf8-at-end
    invalid/encoding/bad-utf8-in-array
    invalid/encoding/bad-utf8-in-comment
    invalid/encoding/bad-utf8-in-multiline
    invalid/encoding/bad-utf8-in-multiline-literal
    invalid/encoding/bad-utf8-in-string
    invalid/encoding/bad-utf8-in-string-literal
    invalid/encoding/bom-not-at-start-01
    invalid/encoding/bom-not-at-start-02
    invalid/encoding/ideographic-space
    invalid/encoding/utf16-bom
    invalid/encoding/utf16-comment
    invalid/encoding/utf16-key
    invalid/float/double-dot-01
    invalid/float/double-dot-02
    invalid/float/exp-dot-01
    invalid/float/exp-dot-02
    invalid/float/exp-dot-03
    invalid/float/exp-double-e-01
    invalid/float/exp-double-e-02
    invalid/float/exp-double-us
    invalid/float/exp-leading-us
    invalid/float/exp-trailing-us
    invalid/float/exp-trailing-us-01
    invalid/float/exp-trailing-us-02
    invalid/float/inf-capital
    invalid/float/inf-incomplete-01
    invalid/float/inf-incomplete-02
    invalid/float/inf-incomplete-03
    invalid/float/inf_underscore
    invalid/float/leading-dot
    invalid/float/leading-dot-neg
    invalid/float/leading-dot-plus
    invalid/float/leading-us
    invalid/float/leading-zero
    invalid/float/leading-zero-neg
    invalid/float/leading-zero-plus
    invalid/float/nan-capital
    invalid/float/nan-incomplete-01
    invalid/float/nan-incomplete-02
    invalid/float/nan-incomplete-03
    invalid/float/nan_underscore
    invalid/float/trailing-dot
    invalid/float/trailing-dot-01
    invalid/float/trailing-dot-02
    invalid/float/trailing-dot-min
    invalid/float/trailing-dot-plus
    invalid/float/trailing-exp
    invalid/float/trailing-exp-dot
    invalid/float/trailing-exp-minus
    invalid/float/trailing-exp-plus
    invalid/float/trailing-us
    invalid/float/trailing-us-exp-01
    invalid/float/trailing-us-exp-02
    invalid/float/us-after-dot
    invalid/float/us-before-dot
    invalid/inline-table/bad-key-syntax
    invalid/inline-table/double-comma
    invalid/inline-table/duplicate-key-01
    invalid/inline-table/duplicate-key-02
    invalid/inline-table/duplicate-key-03
    invalid/inline-table/duplicate-key-04
    invalid/inline-table/empty-01
    invalid/inline-table/empty-02
    invalid/inline-table/empty-03
    invalid/inline-table/linebreak-01
    invalid/inline-table/linebreak-02
    invalid/inline-table/linebreak-03
    invalid/inline-table/linebreak-04
    invalid/inline-table/no-close-01
    invalid/inline-table/no-close-02
    invalid/inline-table/no-comma-01
    invalid/inline-table/no-comma-02
    invalid/inline-table/overwrite-01
    invalid/inline-table/overwrite-02
    invalid/inline-table/overwrite-03
    invalid/inline-table/overwrite-04
    invalid/inline-table/overwrite-05
    invalid/inline-table/overwrite-06
    invalid/inline-table/overwrite-07
    invalid/inline-table/overwrite-08
    invalid/inline-table/overwrite-09
    invalid/inline-table/overwrite-10
    invalid/inline-table/trailing-comma
    invalid/integer/capital-bin
    invalid/integer/capital-hex
    invalid/integer/capital-oct
    invalid/integer/double-sign-nex
    invalid/integer/double-sign-plus
    invalid/integer/double-us
    invalid/integer/incomplete-bin
    invalid/integer/incomplete-hex
    invalid/integer/incomplete-oct
    invalid/integer/invalid-bin
    invalid/integer/invalid-hex-01
    invalid/integer/invalid-hex-02
    invalid/integer/invalid-hex-03
    invalid/integer/invalid-oct
    invalid/integer/leading-us
    invalid/integer/leading-us-bin
    invalid/integer/leading-us-hex
    invalid/integer/leading-us-oct
    invalid/integer/leading-zero-01
    invalid/integer/leading-zero-02
    invalid/integer/leading-zero-03
    invalid/integer/leading-zero-sign-01
    invalid/integer/leading-zero-sign-02
    invalid/integer/leading-zero-sign-03
    invalid/integer/negative-bin
    invalid/integer/negative-hex
    invalid/integer/negative-oct
    invalid/integer/positive-bin
    invalid/integer/positive-hex
    invalid/integer/positive-oct
    invalid/integer/text-after-integer
    invalid/integer/trailing-us
    invalid/integer/trailing-us-bin
    invalid/integer/trailing-us-hex
    invalid/integer/trailing-us-oct
    invalid/integer/us-after-bin
    invalid/integer/us-after-hex
    invalid/integer/us-after-oct
    invalid/key/after-array
    invalid/key/after-table
    invalid/key/after-value
    invalid/key/bare-invalid-character-01
    invalid/key/bare-invalid-character-02
    invalid/key/dot
    invalid/key/dotdot
    invalid/key/dotted-redefine-table-01
    invalid/key/dotted-redefine-table-02
    invalid/key/duplicate-keys-01
    invalid/key/duplicate-keys-02
    invalid/key/duplicate-keys-03
    invalid/key/duplicate-keys-04
    invalid/key/duplicate-keys-05
    invalid/key/duplicate-keys-06
    invalid/key/duplicate-keys-07
    invalid/key/duplicate-keys-08
    invalid/key/duplicate-keys-09
    invalid/key/empty
    invalid/key/end-in-escape
    invalid/key/escape
    invalid/key/hash
    invalid/key/multiline-key-01
    invalid/key/multiline-key-02
    invalid/key/multiline-key-03
    invalid/key/multiline-key-04
    invalid/key/newline-01
    invalid/key/newline-02
    invalid/key/newline-03
    invalid/key/newline-04
    invalid/key/newline-05
    invalid/key/newline-06
    invalid/key/no-eol-01
    invalid/key/no-eol-02
    invalid/key/no-eol-03
    invalid/key/no-eol-04
    invalid/key/no-eol-05
    invalid/key/no-eol-06
    invalid/key/no-eol-07
    invalid/key/only-float
    invalid/key/only-int
    invalid/key/only-str
    invalid/key/open-bracket
    invalid/key/partial-quoted
    invalid/key/quoted-unclosed-01
    invalid/key/quoted-unclosed-02
    invalid/key/single-open-bracket
    invalid/key/space
    invalid/key/special-character
    invalid/key/start-bracket
    invalid/key/start-dot
    invalid/key/two-equals-01
    invalid/key/two-equals-02
    invalid/key/two-equals-03
    invalid/key/without-value-01
    invalid/key/without-value-02
    invalid/key/without-value-03
    invalid/key/without-value-04
    invalid/key/without-value-05
    invalid/key/without-value-06
    invalid/key/without-value-07
    invalid/spec-1.0.0/inline-table-2-0
    invalid/spec-1.0.0/inline-table-3-0
    invalid/spec-1.0.0/key-value-pair-1
    invalid/spec-1.0.0/keys-2
    invalid/spec-1.0.0/string-4-0
    invalid/spec-1.0.0/string-7-0
    invalid/spec-1.0.0/table-9-0
    invalid/spec-1.0.0/table-9-1
    invalid/string/bad-byte-escape
    invalid/string/bad-concat
    invalid/string/bad-escape-01
    invalid/string/bad-escape-02
    invalid/string/bad-escape-03
    invalid/string/bad-escape-04
    invalid/string/bad-escape-05
    invalid/string/bad-hex-esc-01
    invalid/string/bad-hex-esc-02
    invalid/string/bad-hex-esc-03
    invalid/string/bad-hex-esc-04
    invalid/string/bad-hex-esc-05
    invalid/string/bad-multiline
    invalid/string/bad-slash-escape
    invalid/string/bad-uni-esc-01
    invalid/string/bad-uni-esc-02
    invalid/string/bad-uni-esc-03
    invalid/string/bad-uni-esc-04
    invalid/string/bad-uni-esc-05
    invalid/string/bad-uni-esc-06
    invalid/string/bad-uni-esc-07
    invalid/string/bad-uni-esc-ml-01
    invalid/string/bad-uni-esc-ml-02
    invalid/string/bad-uni-esc-ml-03
    invalid/string/bad-uni-esc-ml-04
    invalid/string/bad-uni-esc-ml-05
    invalid/string/bad-uni-esc-ml-06
    invalid/string/bad-uni-esc-ml-07
    invalid/string/basic-byte-escapes
    invalid/string/basic-multiline-out-of-range-unicode-escape-01
    invalid/string/basic-multiline-out-of-range-unicode-escape-02
    invalid/string/basic-multiline-quotes
    invalid/string/basic-multiline-unknown-escape
    invalid/string/basic-out-of-range-unicode-escape-01
    invalid/string/basic-out-of-range-unicode-escape-02
    invalid/string/basic-unknown-escape
    invalid/string/literal-multiline-quotes-01
    invalid/string/literal-multiline-quotes-02
    invalid/string/missing-quotes
    invalid/string/missing-quotes-array
    invalid/string/missing-quotes-inline-table
    invalid/string/multiline-bad-escape-01
    invalid/string/multiline-bad-escape-02
    invalid/string/multiline-bad-escape-03
    invalid/string/multiline-bad-escape-04
    invalid/string/multiline-escape-space-01
    invalid/string/multiline-escape-space-02
    invalid/string/multiline-lit-no-close-01
    invalid/string/multiline-lit-no-close-02
    invalid/string/multiline-lit-no-close-03
    invalid/string/multiline-lit-no-close-04
    invalid/string/multiline-no-close-01
    invalid/string/multiline-no-close-02
    invalid/string/multiline-no-close-03
    invalid/string/multiline-no-close-04
    invalid/string/multiline-no-close-05
    invalid/string/multiline-quotes-01
    invalid/string/no-close-01
    invalid/string/no-close-02
    invalid/string/no-close-03
    invalid/string/no-close-04
    invalid/string/no-close-05
    invalid/string/no-close-06
    invalid/string/no-close-07
    invalid/string/no-close-08
    invalid/string/no-close-09
    invalid/string/no-close-10
    invalid/string/no-open-01
    invalid/string/no-open-02
    invalid/string/no-open-03
    invalid/string/no-open-04
    invalid/string/no-open-05
    invalid/string/no-open-06
    invalid/string/no-open-07
    invalid/string/no-open-08
    invalid/string/text-after-string
    invalid/string/wrong-close
    invalid/table/append-with-dotted-keys-01
    invalid/table/append-with-dotted-keys-02
    invalid/table/append-with-dotted-keys-03
    invalid/table/append-with-dotted-keys-04
    invalid/table/append-with-dotted-keys-05
    invalid/table/append-with-dotted-keys-06
    invalid/table/append-with-dotted-keys-07
    invalid/table/array-empty
    invalid/table/array-implicit
    invalid/table/array-no-close-01
    invalid/table/array-no-close-02
    invalid/table/array-no-close-03
    invalid/table/array-no-close-04
    invalid/table/bare-invalid-character-01
    invalid/table/bare-invalid-character-02
    invalid/table/dot
    invalid/table/dotdot
    invalid/table/duplicate-key-01
    invalid/table/duplicate-key-02
    invalid/table/duplicate-key-03
    invalid/table/duplicate-key-04
    invalid/table/duplicate-key-05
    invalid/table/duplicate-key-06
    invalid/table/duplicate-key-07
    invalid/table/duplicate-key-08
    invalid/table/duplicate-key-09
    invalid/table/duplicate-key-10
    invalid/table/empty
    invalid/table/newline-01
    invalid/table/newline-02
    invalid/table/newline-03
    invalid/table/newline-05
    invalid/table/no-close-03
    invalid/table/overwrite-array-in-parent
    invalid/table/overwrite-bool-with-array
    invalid/table/overwrite-with-deep-table
    invalid/table/redefine-02
    invalid/table/redefine-03
    invalid/table/rrbrace
    invalid/table/super-twice
)

./toml-test-* test -decoder ./toml_parser -skip-must-err -errors expected_errors.toml $(printf " -skip %s" ${tests_to_skip[@]}) "$@"
