#!/bin/bash

set -x
set +e

ls -lahtr

#find -name 'ssh*'  # --> /usr/sbin/sshd

ip link
ip link set dev eth0 up
ip link

#ifconfig eth0 up

dhclient -v eth0

cat /etc/resolv.conf
#echo "nameserver 8.8.8.8" > /etc/resolv.conf
#cat /etc/resolv.conf

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs devtmpfs /dev

curl example.com

[ -f /etc/ssh/ssh_host_ed25519_key ] || ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ""

/usr/sbin/sshd -D
