#!/bin/bash
#
# This script creates design.png from the libreoffice file.

set -ex
libreoffice --headless --convert-to png design.odg
convert design.png -trim +repage -bordercolor white -border 50 design.png
