on:
  push:
    branches:
      - main
  pull_request_target:

jobs:
  fix-line-endings:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      # git-auto-commit-action is a bit tricky to use, see its README
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - run: sudo apt install -y dos2unix
      - run: dos2unix $(git ls-files | grep -vx tests/should_succeed/crlf.jou)
      - run: unix2dos tests/should_succeed/crlf.jou
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Change files to use LF line endings"

