on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        llvm-version: [11, 13]
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y llvm-${{ matrix.llvm-version }}-dev clang-${{ matrix.llvm-version }} make valgrind
    - run: make test

  valgrind:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        llvm-version: [11, 13]
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y llvm-${{ matrix.llvm-version }}-dev clang-${{ matrix.llvm-version }} make valgrind
    - run: make valgrind

  fuzzer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        llvm-version: [11, 13]
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y llvm-${{ matrix.llvm-version }}-dev clang-${{ matrix.llvm-version }} make valgrind
    - run: ./fuzzer.sh
