on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y llvm-11-dev clang-11 make valgrind
    - run: make test

  valgrind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y llvm-11-dev clang-11 make valgrind
    - run: make valgrind

  fuzzer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y llvm-11-dev clang-11 make valgrind
    - run: ./fuzzer.sh
