name: "Linux"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Testing all levels because there was a bug that only happened with -O1. (#224)
        # Please keep in sync with valgrind.yml and macos.yml
        params:
          # Oldest version: all opt levels
          - { llvm-version: 15, opt-level: '-O0' }
          - { llvm-version: 15, opt-level: '-O1' }
          - { llvm-version: 15, opt-level: '-O2' }
          - { llvm-version: 15, opt-level: '-O3' }
          # Most versions: just one opt level to save time
          - { llvm-version: 16, opt-level: '-O1' }
          - { llvm-version: 17, opt-level: '-O1' }
          - { llvm-version: 18, opt-level: '-O1' }
          - { llvm-version: 19, opt-level: '-O1' }
          # Latest version: all opt levels
          # TODO: LLVM 21 is not available from apt yet.
          - { llvm-version: 20, opt-level: '-O0' }
          - { llvm-version: 20, opt-level: '-O1' }
          - { llvm-version: 20, opt-level: '-O2' }
          - { llvm-version: 20, opt-level: '-O3' }
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Fetch the whole Git history for bootstrapping

      # Using "sudo apt install ..." redownloads the same packages every time
      # and often gets stuck for some reason. Let's hack around it by caching
      # the downloaded packages.
      - name: Get ready to install apt packages
        run: |
          # Make sure apt knows about latest versions of the packages
          sudo apt update

          # Save list of packages we're installing so that we don't need to repeat it
          echo llvm-${{ matrix.params.llvm-version }}-dev clang-${{ matrix.params.llvm-version }} make valgrind liblzma-dev | tee apt-gonna-install.txt

          # Create a cache key that depends on all details of packages that we
          # will install (name, version, architecture). So if what we install
          # changes for any reason, e.g. new version of package is available,
          # then the cache is not reused.
          #
          # This shows output with a bunch of "Inst" lines, but nothing is
          # actually installed here. Each "Inst" line represents a package that
          # apt would install.
          apt-get --dry-run install $(cat apt-gonna-install.txt) | grep ^Inst | tee apt-cache-key-input.txt

      - name: Cache apt packages
        uses: actions/cache@v5
        with:
          path: apt-cache
          key: apt-${{ hashFiles('apt-cache-key-input.txt') }}

      - name: Install apt packages
        run: |
          # Use cached files when installing (if any)
          sudo cp -v apt-cache/*.deb /var/cache/apt/archives/ || true

          # Actually install packages. We saved list of package names earlier.
          # Let's use them and also tell apt to not delete the .deb files once
          # it has finished installing them.
          sudo apt install -o APT::Keep-Downloaded-Packages=true $(cat apt-gonna-install.txt)

          # Recreate apt-cache directory with what we actually want to cache now
          rm -rvf apt-cache
          mkdir -v apt-cache
          cp -v /var/cache/apt/archives/*.deb apt-cache/

      - name: "Select LLVM version"
        run: echo "LLVM_CONFIG=llvm-config-${{ matrix.params.llvm-version }}" >> $GITHUB_ENV
      - name: "Compile and test"
        run: ./runtests.sh --verbose --jou-flags "${{ matrix.params.opt-level }}"
      - name: "Compile the compiler with itself"
        run: ./jou -o jou2 compiler/main.jou && mv jou2 jou
      - name: "Compile and test again"
        run: ./runtests.sh --verbose --jou-flags "${{ matrix.params.opt-level }}"
      # Valgrinding all files is slow, but let's valgrind the hello world.
      # This is enough to catch many bugs.
      #
      # We also have a separate, "full" valgrind run. See valgrind.yml.
      - name: "Run hello world with valgrind"
        run: ./runtests.sh --verbose --jou-flags "${{ matrix.params.opt-level }}" --valgrind hello
      - run: tests/toml/run.sh --jou-flags "${{ matrix.params.opt-level }}"
      - name: "Run the new test runner"
        run: make joutest && ./joutest --verbose
      - name: "Run the new test runner with valgrind"
        # No leak checking flags here, currently joutest is a bit leaky and I'm
        # not sure if I want to fix it. The OS frees all memory anyway when
        # joutest exits.
        run: valgrind --error-exitcode=1 ./joutest --verbose
